name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
        #checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

        #Set up Nodejs
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          
        #Install NodeJS dependencies
      - name: Install NodeJS dependencies
        run: npm install

        #Sonarqube Analysi
   #   - name: Sonarqube Scan
   #     uses: sonarsource/sonarqube-scan-action@master
   #     env:
   #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    #      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
        #Docker Image Build
      - name: Docker image build
        run: |
          docker build -t actions-app:${{ github.sha}} .
          docker tag actions-app:${{ github.sha}} ${{ secrets.ECR_REPOSITORY_URI}}/actions-cicd:latest
          docker tag actions-app:${{ github.sha}} ${{ secrets.DOCKER_USERNAME}}/actions-cicd:latest
        

        #Trivy Scan
      - name: Trivy Scan
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image actions-app:${{ github.sha}}

       #set up AWS credentias
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
          
     #Install aws cli
      - name: Install AWS CLI v2
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2 # Specify the desired AWS CLI version (e.g., 2 for v2)
          verbose: false
          arch: amd64
      - name: Use AWS CLI
        run: |
          aws --version
        
        #Login AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_REPOSITORY_URI}}
      
      #push image into ECR
      - name: Push image to Amazon ECR
        run: |
          docker push ${{secrets.ECR_REPOSITORY_URI}}/actions-cicd:latest
        env:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}

    #Push image to dockerhub
      - name: Push image to Dockerhub
        run:
          docker push ${{ secrets.DOCKER_USERNAME}}/actions-cicd:latest
    #update kubeconfig
      - name: Update Kubeconfig
        run: aws eks --region ${{secrets.AWS_REGION}} update-kubeconfig --name action-eks-cluster

    #Install Kubectl
      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
          chmod +x kubectl
          mv ./kubectl /usr/local/bin/kubectl
          
    #Deploy to Amazon EKS
      - name: Deploy to EKS
        run: |
          kubectl apply -f k8s-manifests/deployment.yaml
          kubectl apply -f k8s-manifests/service.yaml
          
      

        
