name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
        #checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

        #Set up Nodejs
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '14'
          
        #Install NodeJS dependencies
      - name: Install NodeJS dependencies
        run: npm install

        #Sonarqube Analysi
      - name: Sonarqube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          
        #Docker Image Build
      - name: Docker image build
        run: docker build -t $GITHUB_SHA .

        #Trivy Scan
      - name: Trivy Scan
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image  $GITHUB_SHA

       #set up AWS credentias
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{secrets.AWS_REGION}}
          
        
        #Login AWS ECR
      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_REPOSITORY_URI}}

        
